### ISSUE TITLE
To-Do List [BFBC2Toolkit]

### ISSUE THREAD

**Issue by AnirohDev** [HeicoDev/FBOneTools#1]
High priority

- [ ] Add game profiles for BFBC, BFBC2 & BF1943 (PS3 & Xbox 360 version)
- [ ] Properly merge several dirs/archives in one TreeView for game profiles
- [ ] Ability to switch between duplicated files (same files that exist in several archives)

Medium priority

- [x] Fix freezing when loading a game profile
- [ ] Make BFBC2 File Converter and Porter completely standalone
- [ ] Make folders removeable
- [x] Add search history to "Find and Replace" window

Low priority

- [x] Add update check
- [ ] Change "highlight current line", "code folding" and "tabs" style for text editor
- [ ] Handle DDS files with DirectX to support older operating systems than Windows 10 (probably too difficult for me)
- [ ] Handle Bink files with the functions provided by binkw32.dll so no 3rd party codec is required. (probably too difficult for me)
