### ISSUE TITLE
To-Do List [BFBC2ModLoader]

### ISSUE THREAD

**Issue by HeicoDev** [HeicoDev/FBOneTools#3]
High priority

- [x] Fix that the error.log file can't be accessed on startup
- [x] Fix that mods with a similar name can lead to a conflict

Medium priority

- [ ] Remove Python script server.pyw and implement a solution to contact game servers natively in C#

Low priority

- [x] Fix freezing of loading window on startup
- [ ] Display mod summary in the info box at the right side
- [ ] Re-add news window
- [x] Improve exception handling
