### ISSUE TITLE
To-Do List [Shared]

### ISSUE THREAD

**Issue by HeicoDev** [HeicoDev/FBOneTools#5]
**Note:** "Shared" means that this list is related to BFBC2Toolkit and BFBC2ModLoader. 
It is not necessarily related to the BFBC2Shared library.

Medium priority

- [x] Add a check if Python is installed
- [x] Add option to select/change the path of the Python installation 
- [x] Improve Python script handling (mainly to be more fail proof)

Low priority

- [ ] Adjust scrollbar style to be more visible when hovering over it with the mouse
- [ ] XAML part of both tools is a copy & paste mess. I really need to learn that stuff properly
- [ ] Need to comment the code to make it more understandable for other people
